backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: "https://jogaukazka.netlify.app"
root_url: "/admin/"
publish_mode: editorial_workflow

collections:
  - name: "aktuality"
    label: "Aktuality"
    folder: "content/aktuality"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Nadpis"
        name: "title"
        widget: "string"
      - label: "Obsah"
        name: "body"
        widget: "markdown"
      - label: "Obrázek"
        name: "image"
        widget: "image"
        required: false